import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&amp;display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/icon?family=Material+Icons+Outlined"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:wght,FILL@100..700,0..1&amp;display=swap"
          rel="stylesheet"
        />
      </head>
      <body 
        className="bg-background-light min-h-screen transition-colors duration-200"
        suppressHydrationWarning
      >
        {/*} Header 
        <header className="w-full py-6 bg-white shadow-sm transition-colors duration-200">
          <div className="max-w-6xl mx-auto px-6 flex justify-between items-center">
            <div className="flex items-center space-x-2">
              <div className="w-10 h-10 bg-primary rounded-full flex items-center justify-center">
                <span className="text-white font-bold text-xl">L</span>
              </div>
              <span className="text-xl font-bold tracking-tight text-slate-800 uppercase">
                Banco de XXX
              </span>
            </div>
            <button className="p-2 text-primary hover:bg-slate-100 rounded-full transition-colors">
              <span className="material-icons-outlined">home</span>
            </button>
          </div>
        </header>
        */}
        {children}
        <Toaster position="top-center" />
      </body>
    </html>
  );
}
